@startuml

hide empty fields
hide empty members
'left to right direction

package item {
    class Condition {
        + id: integer
        + name: string
    }

    class Category {
        + id: integer
        + name: string
    }

    class Item {
        + id: integer
        + condition: Condition
        + country: Country
        + accepted_offer: Offer | null
        + views: integer
        + name: string
        + description: string
        + image_url: string
        + zip: string
        + sold_at: datetime
        + published_at: datetime
        + created_at: datetime
        + updated_at: datetime
    }
    note bottom of Item
        sold_at is NULL until sold.
        Item is for sale when
        published_at has passed
        and sold_at is NULL.
    end note

    class CategoryItem {
        + id: integer
        + category: Category
        + item: Item
    }

    class Offer {
        + id: integer
        + item: Item
        + user: User
        + amount: integer
        + date: datetime
        + accepted: bool
    }
    note bottom of Offer
        amount is in ISK currency, no aurar!
    end note


    class Sale {
        + id: integer
        + item: Item
        + buyer: User
        + seller: User
        + offer: Offer
        + country: Country
        + amount: amount
        + full_name: string
        + street_name: string
        + house_number: string
        + city: string
        + zip: string
        + fill_from_contact(contact: Contact)
    }
    note bottom of Sale
        Contact information is "rendered"
        on the sale so the state of the
        contact information doesn't
        change in the future.
        Same with amount, for peace of mind.
    end note
}
together {
package Django {
    class User
}

package user {
    class UserProfile

    class Country

    class Contact
    class Rating
}
package messaging {
    class Message
    class MessageMeta
}
}
Offer <|--|> Item
Offer --|> User

Item --|> Condition
Item --|> Country


Sale --|> Item
Sale --|> User
Sale --|> Offer
Sale --|> Country
Sale --- Contact

CategoryItem --|> Category
CategoryItem --|> Item

MessageMeta --- Item
MessageMeta --- Offer

Country -[hidden]- Contact
Contact -[hidden]- UserProfile
UserProfile -[hidden]- Rating

messaging -down[hidden]- Django
Django -down[hidden]- user

@enduml